name: Build & Debug

on:
  push:
    branches-ignore: [ release ]
  pull_request:
    branches-ignore: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        python --version
        python -m pip install conan
        pip3 install conan

